CREATE TABLE IF NOT EXISTS COURSE(
    COURSE_ID UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL UNIQUE,
    DESCRIPTION text NOT NULL,
    DEPARTMENT VARCHAR(255) NOT NULL,
    TEACHER_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDENT_COURSE(
    STUDENT_ID UUID NOT NULL REFERENCES STUDENT(STUDENT_ID),
    COURSE_ID UUID NOT NULL REFERENCES COURSE(COURSE_ID),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    GRADE INTEGER CHECK (GRADE BETWEEN 0 AND 100),
    UNIQUE (STUDENT_ID, COURSE_ID)
);

